version: '3.1'

services:
  nginx:
    container_name: mstaff-micro__front-symfo-2__prod__nginx
    image: nginx:alpine
    working_dir: /application
    depends_on:
      - 'php-fpm'
    volumes:
      - './public:/application/public'
      - './docker/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - mstaff-micro.network

  php-fpm:
    container_name: mstaff-micro__front-symfo-2__prod__php-fpm
    build: docker/prod/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './docker/prod/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    networks:
      - mstaff-micro.network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

networks:
  mstaff-micro.network:
    external: true