version: '3.1'

services:
  php-fpm:
    container_name: mstaff-micro__front-symfo-2__dev__php-fpm
    build: docker/dev
    working_dir: /application
    ports:
      - '21001:8000'
    volumes:
      - .:/application
    networks:
      - mstaff-micro.network

networks:
  mstaff-micro.network:
    external: true